services:
  postgres-main:
    image: postgres:18
    container_name: sansi-svc-postgres-main
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sansi
    ports:
      - "5501:5432"
    volumes:
      - $HOME/.docker-volumes/sansi-svc/postgres-main:/var/lib/postgresql/18/docker
      - ./db/init:/docker-entrypoint-initdb.d

  postgres-test:
    image: postgres:18
    container_name: sansi-svc-postgres-test
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sansi
    ports:
      - "5502:5432"
    volumes:
      - $HOME/.docker-volumes/sansi-svc/postgres-test:/var/lib/postgresql/18/docker
      - ./db/init:/docker-entrypoint-initdb.d
